### ISSUE TITLE
question, for WinXP kernel

### ISSUE THREAD

**Issue by iyutr** [rustyx/nobuzz#1]
I am sorry for such silly question, what do you think about refactoring this program "Nobuzz" for WinXP kernel?  no chances you'll make it for obsolete OS?

**Comment by rustyx** [comment]
Oh my. WinXP is not supported but should work. Is it not working?

**Comment by iyutr** [comment]
In my test, this did not work. Of course, you are not obliged to make a build for the unsupported XP, I just asked, if it's not difficult to.

"c:\SysinternalsSuite\Clockres.exe"
Maximum timer interval: 15.625 ms
Minimum timer interval: 1.000 ms
Current timer interval: 0.977 ms

Else close the issue, thank you.

**Comment by iyuter** [comment]
Sorry, it is written in the description: "it works only on CPU sleep state noise". ?
I thought it works when OS Windows runs, by hooking the call "timeBeginPeriod".
If it is only for the SleepMode, for me this program is not needed. 
I wanted this for energy-saving purpose, when browsers work.

**Comment by rustyx** [comment]
After some investigation it seems Chrome in addition to `timeBeginPeriod` (which *is* hooked) uses DirectShow, which isn't hooked. That one also sets the 1ms timer interval and at the moment I don't know how to hook it, unfortunately. Ideas and additional details are welcome.

**Comment by iyuter** [comment]
Sorry, I'm ignorant of programming. Googling indicated on the culprit.  C:\Windows\System32\quartz.dll
Maybe hook of SetSystemTimeAdjustment or so, but it is not certain. I am a noob in it.

**Comment by iyuter** [comment]
I have not found any analogues to your program. Here is my report. 
On WinXP Nobuzz does not work. At my PC usual clock rate: 15.6 ms (64 Hz). 
Running different browsers (Firefox, Chrome, Opera Presto): 1.9 ms (511 Hz) ~ 0.9 ms (1023 Hz).

On Win7, running different browsers: clock rate most often: 10 ms (100 Hz). 
Sometimes for a moment jumps into: 1 ms (1000 Hz).

Test was made with: Sysinternals Clockres.exe, and power management tool IBM_ECW (http://bertrand.deo.free.fr/IBM_EC/index_e.html).
